
--EXEMPLO OPERADOR IGUAL =
SELECT * FROM HR.EMPLOYEES a
WHERE a.JOB_ID='IT_PROG';

--EXEMPLO OPERADOR IGUAL =
SELECT * FROM HR.EMPLOYEES a
WHERE a.SALARY='9000';


--EXEMPLO OPERADOR MAIOR > 

SELECT * FROM HR.EMPLOYEES a
WHERE a.HIRE_DATE>'03/02/06'
order by  a.HIRE_DATE asc;


--EXEMPLO OPERADOR MAIOR > 

SELECT * FROM HR.EMPLOYEES a
WHERE a.SALARY>'9000'
order by a.SALARY asc ;

--EXEMPLO OPERADOR MENOR < 


SELECT * FROM HR.EMPLOYEES a
WHERE a.HIRE_DATE<'03/02/06'
order by  a.HIRE_DATE asc;
--EXEMPLO OPERADOR MENOR < 

SELECT * FROM HR.EMPLOYEES a
WHERE a.SALARY<'9000'
order by a.SALARY asc;

--EXEMPLO OPERADOR MAIOR IGUAL>= 

SELECT * FROM HR.EMPLOYEES a
WHERE a.SALARY>='9000'
order by a.SALARY asc;

--EXEMPLO OPERADOR MAIOR IGUAL>= 
SELECT * FROM HR.EMPLOYEES a
WHERE a.HIRE_DATE>='05/02/06'
order by  a.HIRE_DATE asc;

--EXEMPLO OPERADOR MENOR IGUAL <= 

SELECT * FROM HR.EMPLOYEES a
WHERE a.HIRE_DATE<='05/02/06'
order by  a.HIRE_DATE asc;

--EXEMPLO OPERADOR MENOR IGUAL <= 

SELECT * FROM HR.EMPLOYEES a
WHERE a.SALARY<='9000'
order by a.SALARY desc;

--EXEMPLO OPERADOR DIFERENTE <> 
SELECT * FROM HR.EMPLOYEES a
WHERE a.JOB_ID<>'IT_PROG';

--EXEMPLO OPERADOR DIFERENTE <> 
SELECT * FROM HR.EMPLOYEES a
WHERE a.MANAGER_ID<>'100';

--EXEMPLO COMBINANDO OPERADORES

SELECT * FROM HR.EMPLOYEES a
WHERE a.JOB_ID='IT_PROG'
AND a.SALARY>4800
AND a.MANAGER_ID='103';
